apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: skillpulse-app:/Service:dev/mysql-service
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"skillpulse-app:/Service:dev/mysql-service"},"name":"mysql-service","namespace":"dev"},"spec":{"ports":[{"port":3306,"targetPort":3306}],"selector":{"app":"mysql"}}}
  creationTimestamp: "2026-05-16T18:24:00Z"
  name: mysql-service
  namespace: production
spec:
  clusterIP: 10.100.225.244
  clusterIPs:
  - 10.100.225.244
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: ClusterIP

