name: CD Helm Deployment

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  deploy:
    name: Deploy To EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ap-south-1 \
            --name skillpulse-eks

      - name: Helm Upgrade Frontend
        run: |
          helm upgrade --install frontend ./helm/frontend -n dev

      - name: Helm Upgrade Backend
        run: |
          helm upgrade --install backend ./helm/backend -n dev

      - name: Verify Deployment
        run: |
          kubectl get pods -n dev
          kubectl get svc -n dev
